import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
	return (
		<>
			<Head>
				<title>JulianRiedinger - Frontend Developer</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<div
					className="relative flex flex-col lg:flex-row items-center 
          justify-center lg:justify-around h-screen overflow-hidden"
				>
					<div className="text-center">
						<h1>Hola! Soy Julian Riedinger</h1>
						<h2>Frontend Developer</h2>
						<a href="#" download="/cv-final.pdf" className="btn-cv">
							Descargar CV
						</a>
					</div>
					<div className="relative w-60 h-60 mt-5 md:h-80 md:w-80">
						<Image
							src="/yo.jpeg"
							alt="Julian Riedinger"
							fill
							className="rounded-full aspect-square object-cover"
						/>
					</div>
					<video
						src="/background.mp4"
						autoPlay
						loop
						muted
						className="absolute -z-10 w-auto 
              min-w-full min-h-full max-w-none"
					></video>
				</div>
			</main>
		</>
	);
}
